n=int(input("enter the first number "))
m=int(input("enter the second number "))
print("addition :" ,n+m)
print("subtraction :",n-m)
print("multiplication :", n*m)
print("divison :", n/m)
print("floor divison :" ,n//m)